'use strict';
export const CHANGE_FIELD = "CHANGE_FIELD";
export const REQUEST_WEATHER = "REQUEST_WEATHER";
export const RESPONSE_WEATHER = "RESPONSE_WEATHER";
export const FAIL_RESPONSE = "FAIL_RESPONSE";